### ISSUE TITLE
Error when installing with foundry as solidity framework

### ISSUE THREAD

**Issue by Pabl0cks** [damianmarti/ponder-se2-extension#1]
Hardhat installation and the deployed SE-2 instance with ponder it's working great! 

When trying to install selecting Foundry, I'm getting this error on Windows+Git bash:

```
× 📡 Initializing Git repository and submodules [FAILED: Failed to initialize git repository]
ERROR Error occurred Error: Failed to initialize git repository
    at createFirstGitCommit (file:///C:/Users/Pablo/AppData/Local/npm-cache/_npx/85f97c58a7d429b9/node_modules/create-eth/dist/cli.js:395:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Task.run (file:///C:/Users/Pablo/AppData/Local/npm-cache/_npx/85f97c58a7d429b9/node_modules/listr2/dist/index.js:2056:11) {
  [cause]: "Cloning into 'E:/GitHub/se2-ponder-foundry/packages/foundry/lib/forge-std'...\n" +
    'error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)\n' +
    'error: 10 bytes of body are still expected\n' +
    'fetch-pack: unexpected disconnect while reading sideband packet\n' +
    'fatal: early EOF\n' +
    'fatal: fetch-pack: invalid index-pack output\n' +
    "fatal: clone of 'https://github.com/foundry-rs/forge-std' into submodule path 'E:/GitHub/se2-ponder-foundry/packages/foundry/lib/forge-std' failed\n" +
    'Error: \n' +
    'git submodule exited with code 128'
}
Uh oh! 😕 Sorry about that! Exiting...
```

**Comment by damianmarti** [comment]
I'm getting a similar error, but it's throwing even if I just use ```npx create-eth@latest```

Can you please check if you get the same error running this?

**Comment by Pabl0cks** [comment]
I tried it but was working for me. 

Will check again later when I'm back to the computer

==================

Update: Yep, it is installing OK with `npx create-eth@latest` + foundry

pinging @damianmarti because I'm not sure if comment updates send notifications

**Comment by Pabl0cks** [comment]
It's working nicely to me now, closing!
